const express=require("express")
const router=express.Router()
router.use("/api/faculties",require("./facultiesController"))
router.use("/api/departments",require("./departmentController"))
router.use("/api/programs",require("./programController"))
router.use("/api/courses",require("./CoursesController"))
router.use("/api/users",require("./UsersController"))
router.use("/api/doctors",require("./DoctorController"))
router.use("/api/students",require("./StudentController"))
router.use("/api/users/Login",require("./AuthController"))
router.use("/api/rooms",require("./RoomsController"))
router.use("/api/semesters",require("./SemesterController"))
router.use("/api/exams",require("./ExamController"))
module.exports=router