const express=require("express")
const router=express.Router()
router.use("/faculties",require("./facultiesController"))
router.use("/departments",require("./departmentController"))
router.use("/programs",require("./programController"))
router.use("/courses",require("./CoursesController"))
router.use("/users",require("./UsersController"))
router.use("/doctors",require("./DoctorController"))
router.use("/students",require("./StudentController"))
router.use("/users/Login",require("./AuthController"))
router.use("/rooms",require("./RoomsController"))
router.use("/semesters",require("./SemesterController"))
module.exports=router